Reader refactor
michalrentka/zotero-ios pull request #1
Opened 2024-09-09 08:04 UTC by mvasilak

Merges some common logic for PDF and HTML/ePUB readers. New protocols are established where needed.

2024-12-06 14:03 UTC, michalrentka requested changes

2024-12-06 14:03 UTC, michalrentka commented on Zotero/Controllers/Architecture/ReaderCoordinator.swift
All other coordinators are part of the "Scenes" folder, so I guess we should keep that. This can go to Detail folder which shares all readers.

2024-12-06 14:03 UTC, michalrentka commented on Zotero/Controllers/Architecture/ReaderCoordinator.swift
> +protocol ReaderAnnotation {
I'd move this to separate file since it's used throughout the app, not just in this coordinator.

2024-12-06 14:03 UTC, michalrentka commented on Zotero/Controllers/Database/Requests/CreateReaderAnnotationsDbRequest.swift
> +    func addExtraFields(for annotation: Annotation, to item: RItem, database: Realm)
"Extra fields" doesn't sound right. I saw that here and wondered "what extra fields?", each annotation has their own fields.
I get that you wanted to share as much code as possible, so you kept "add fields" and then added "add extra fields" to add their type-specific fields then.

To make it clearer I'd advise this:
- `CreateReaderAnnotationsDbRequest` becomes class instead of protocol
- keep `func addFields(...)` and its implementation
- remove `func addExtraFields(...)`
- `CreateHtmlEpubAnnotationsDbRequest` and `CreateReaderAnnotationsRequest` override `func addFields(...)` and add their own type-specific stuff such as:
```
override func addFields(for annotation: Annotation, toItem item: RItem, database: Realm) {
    super.addFields(for: annotation, toItem: item, database: database)
    type-specific implementation
}
```

2024-12-06 14:03 UTC, michalrentka commented on Zotero/Controllers/Database/Requests/CreateReaderAnnotationsDbRequest.swift
> +                DDLogWarn("CreateReaderAnnotationsDbRequest: user not found for userId \(userId)")
Add annotatoin key and library to this warning

2024-12-09 19:04 UTC, mvasilak commented on Zotero/Controllers/Architecture/ReaderCoordinator.swift
Check https://github.com/michalrentka/zotero-ios/pull/1/commits/9630d1e2eef532bff5b169f9fc014dd7f06ee99d

2024-12-09 19:04 UTC, mvasilak commented on Zotero/Controllers/Architecture/ReaderCoordinator.swift
> +protocol ReaderAnnotation {
Check https://github.com/michalrentka/zotero-ios/pull/1/commits/9630d1e2eef532bff5b169f9fc014dd7f06ee99d

2024-12-09 19:04 UTC, mvasilak commented on Zotero/Controllers/Database/Requests/CreateReaderAnnotationsDbRequest.swift
> +    func addExtraFields(for annotation: Annotation, to item: RItem, database: Realm)
Check https://github.com/michalrentka/zotero-ios/pull/1/commits/af36e6efefd1e74664539731dc5fb1eb3fb74bbb

2024-12-09 19:04 UTC, mvasilak commented on Zotero/Controllers/Database/Requests/CreateReaderAnnotationsDbRequest.swift
> +                DDLogWarn("CreateReaderAnnotationsDbRequest: user not found for userId \(userId)")
Check https://github.com/michalrentka/zotero-ios/pull/1/commits/af36e6efefd1e74664539731dc5fb1eb3fb74bbb

2024-12-10 09:15 UTC, michalrentka approved these changes

2024-12-10 11:52 UTC, merged